### ISSUE TITLE
GitHub categorizes your project as 'Groff'

### ISSUE THREAD

**Issue by floam** [jpcre2/jpcre2#1]
Apologies for bothering you over this, it's very minor.
<img width="668" alt="screenshot 2016-08-31 at 10 37 12 pm" src="https://cloud.githubusercontent.com/assets/291142/18156753/68befb44-6fcd-11e6-928f-f21980d29eae.png">

If you search for [C++ projects related to PCRE](https://github.com/search?l=C%2B%2B&q=pcre&type=Repositories) on GitHub, you can't find this project. It is confusingly ranked as being Groff.

That breakdown is determined by [Linguist, which you can control]. You can use `.gitattributes` to tell it that if files or directories are vendored code from another project, are documentation, or correct it about misidentified files. I [did this on `fish`](https://github.com/fish-shell/fish-shell/blob/master/.gitattributes#L38) because it was mildly annoying that hosting the `pcre2` source tree caused the breakdown of our C vs. C++ code to be all out of whack. And some files that are fish scripts but with different extensions were just marked "other" instead of shell scripts. 

In this case - groff? I think it must be confused - not sure about what. There is a Ruby gem that will analyze your tree and will probably show which files must somehow look like manpages with troff markup to it.
<img width="1028" alt="screenshot 2016-08-31 at 10 36 54 pm" src="https://cloud.githubusercontent.com/assets/291142/18156750/640907e8-6fcd-11e6-8847-c7630cb166c4.png">

**Comment by floam** [comment]
Oh, duh, it's all these files in `autom4te.cache` that end in .1, 2, 3 ... You can tell Linguist to ignore that directory. Or, it's not really something that would be checked into most repos, normally one might just remove them and exclude by `.gitignore`.

**Comment by neurobin** [comment]
Thanks for reporting.. It's 100% on C++ now..

**Comment by floam** [comment]
Cool, hopefully it's a little easier to find the only PCRE2 C++ binding for now. 

Hm, I bet you probably don't need most (all?) these rules. Since it was just that directory for the most part which was huge, nothing else should cause you to get miscategorized again - others may have bad effects.  Like,`*.ac` since `configure.ac` looks original to your project: probably should not mark it vendored (meaning other projects or components of other projects you distribute with your own project). That's likely to cause undesired side-effects for you in the future - e.g. excluded from appearing in your own diffs here: https://github.com/github/linguist/issues/2206 (it was supposed to be doing this already, but it currently is not for "vendored", only "generated", due to a bug - but it's expected to be repaired.) Similarly with .sh - if you have no shellscripts now, but add one, that will also get treated by GitHub as "not interesting/not yours" however they decide to do that down the road.

If the goal is to just keep them out of your language bar thing, it can be marked "ignore" rather than vendored. However the common ones [are already marked vendored automatically]((https://github.com/github/linguist/blob/master/lib/linguist/vendor.yml) - that should get all of the aclocal, etc. stuff for you.

**Comment by neurobin** [comment]
Yeah, actually I don't need to ignore *.ac, *.am and *.sh files. But ignoring (completely) configure, *.in files is important.

Configure and makefiles are important but they are just too big and produces a lot of diffs even for a small change like dumping new version number. And these diffs aren't that useful either.

**Comment by floam** [comment]
I agree totally - although it looks like the [configure script was already excluded automatically](https://github.com/github/linguist/blob/5ac2cdde5053d3cf811a197d35af713e6330e91f/lib/linguist/vendor.yml#L22). This makes sense since nobody writes them by hand - and traditionally a project would not even check the into version control if they can avoid it. We exclude our configure script from our repository, as something we run when making release tarballs. But Makefiles are a good point - ours is checked in because it's handmade - and GitHub doesn't assume for that one, so if you do check in your Makefiles you might want to exclude that manually. 


I believe there are also undocumented ways they are using classification - probably nothing too important though. (Search results)
