### ISSUE TITLE
multiple definition of c++ hpp-only-library

### ISSUE THREAD

**Issue by Kamil93** [jpcre2/jpcre2#10]
Sadly it's hard to use it in complex project, because of multiple definition error. More info on google.
Basically it needs to be splited on hpp and cpp file/s.

https://www.google.pl/search?q=multiple+definition+of+c%2B%2B&oq=multiple+definition+of+c%2B%2B+&aqs=chrome..69i57j0l5.3822j0j7&sourceid=chrome&ie=UTF-8#newwindow=1&q=multiple+definition+of+c%2B%2B+hpp-only-library

**Comment by neurobin** [comment]
For now you can use the [10.27.03](https://github.com/jpcre2/jpcre2/tree/10.27.03) branch. The documentation is [here](https://github.com/jpcre2/jpcre2-doc/tree/10.27.03)

I will look into it.

**Comment by neurobin** [comment]
Can you check out my latest commit at master branch? basically the [header](https://raw.githubusercontent.com/jpcre2/jpcre2/master/src/jpcre2.hpp)

Let me know if it fixes the multiple definition error. If not please post the error messages here.

Regards,
Jahid.

**Comment by Kamil93** [comment]
With this header works fine!

**Comment by Kamil93** [comment]
may I ask about how you did it without spliting into header and source?

**Comment by neurobin** [comment]
This is the rule:

> There can be more than one definition of a class type (clause 9), enumeration type (7.2), inline function with external linkage (7.1.2), class template (clause 14), non-static function template (14.5.5), static data member of a class template (14.5.1.3), member function of a class template (14.5.1.1), or template specialization for which some template parameters are not specified (14.7, 14.5.4) in a program provided that each definition appears in a different translation unit, and provided the definitions satisfy the following requirements....

Some static functions and constants were violating the one definition rule. Those functions needed to be inlined. And for the constants, I wrapped them with inline static functions (I put them in an anonymous namespace in the header that you tested).

You can see [this commit](https://github.com/jpcre2/jpcre2/commit/5d9d87d7eb5c6f15f5713ef7d7795a963f4a4eee#diff-e16fb0ac893004112cef6c96fe5b8a58) for details.
