### ISSUE TITLE
Is the library thread safe?

### ISSUE THREAD

**Issue by grawlee** [jpcre2/jpcre2#13]
Hi guys, Thanks for this - it looks very elegant! I did want to know if jpcre2 was thread safe? 
More precisely, i plan to keep a list of compiled patterns in an object. Then >1 threads will use this object (containing pre compiled patterns) to perform matching on different strings.

Thanks
H

**Comment by neurobin** [comment]
Yes it is...
Though I am not sure about the setLocale function, if you can prove `std::setlocale` is thread safe then it's thread safe too.

So, as long as you don't use setLocale it's **surely** thread safe...

**Comment by neurobin** [comment]
The setLocale function will be removed in next release and an alternative will be provided... to make the whole library thread safe..

**Comment by neurobin** [comment]
No it is not.

**Comment by neurobin** [comment]
You will need to use lock on Regex, RegexMatch and RegexReplace object. Updated the doc to include this info.

**Comment by grawlee** [comment]
Okay No worries. I can work around. But thanks for letting me know man!

**Comment by neurobin** [comment]
JPCRE2 now provides a certain level of thread safety ([details in the doc](https://docs.neurobin.org/jpcre2/index.html#multi-threading)).
