### ISSUE TITLE
Get character positions for matches (only outermost group)

### ISSUE THREAD

**Issue by grawlee** [jpcre2/jpcre2#14]
Hi there, Is there a way to get the starting character positions for all matches in a long subject string.  I need the match's end position as well (in codepoints), but thats straightforward - derived from the match length.

Any way? Advice? I'm keen to use this library! 
Thansk
H

**Comment by neurobin** [comment]
startoffset is set to 0 by default. you can override it with `setStartOffset()` function, and you can get the end offset with `getEndOffset()` function. These two are memebers of RegexMatch class.

**Comment by neurobin** [comment]
You can now pass vectors to catch both start offsets and end offsets.

**Comment by grawlee** [comment]
Thanks man!
