### ISSUE TITLE
undefined reference to `std::ios_base::Init::~Init()' when compiling user code

### ISSUE THREAD

**Issue by catb0t** [jpcre2/jpcre2#15]
I've installed the Ubuntu packages, `libpcre2-dev` and `libpcre2-dbg`, and built this repo from source to find that all the tests pass.

```
============================================================================
Testsuite summary for jpcre2 10.30.01
============================================================================
# TOTAL: 10
# PASS:  10
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
```

But, when I create this file: 
```
#include <iostream>
#include "jpcre2.hpp"

typedef jpcre2::select<char> jp;

int main(void) {

  return 0;
}
```

and compile with `gcc -lpcre2-8 pcre-test.cpp` GCC 6.2  and Clang 3.8.1 complain that 

```
/tmp/cc5IaNGZ.o: In function `__static_initialization_and_destruction_0(int, int)':
jsonminify.cpp:(.text+0x30): undefined reference to `std::ios_base::Init::Init()'
jsonminify.cpp:(.text+0x45): undefined reference to `std::ios_base::Init::~Init()'
collect2: error: ld returned 1 exit status
```

Am I using the wrong command line? How can I fix this?

The `libc6` version is `2.24-9ubuntu2` on Ubuntu 17.04 64-bit.

**Comment by neurobin** [comment]
it should be `g++` not `gcc`:

```bash
g++ pcre-test.cpp -lpcre2-8 
```

**Comment by catb0t** [comment]
Oh, I tried it like `cc -xc++ ...` first and got the same error, I thought `gcc` and `clang` switch to the `++` version automatically if the filename is `cc` or `cpp`, but never mind. Silly mistake, thanks for taking the time.

**Comment by sumitbhimte** [comment]
undefined reference to `std::ios_base::Init::Init()'
collect2.exe: error: ld returned 1 exit status

Getting this error while debugging in Windows VS Code
![Screenshot (168)](https://user-images.githubusercontent.com/43449951/123533183-d95bb480-d730-11eb-8707-8ecbe4a0ae89.png)

**Comment by neurobin** [comment]
@sumitbhimte The answer is the same as before. Use C++ compiler to build (not C compiler).
