### ISSUE TITLE
std::wstring_convert deprecated in C++17

### ISSUE THREAD

**Issue by neurobin** [jpcre2/jpcre2#19]
This issue is to track the deprecation status of `std::wstring_convert` in C++17 and adopt the replacement when available.

**Comment by wbraswell** [comment]
Okay good to have this as a placeholder for the future.

**Comment by neurobin** [comment]
I have decided to deprecate all `std::wstring_convert` related features (`ConvInt`, `ConvUTF`) for `JPCRE2-10.30.xx` and remove them in `JPCRE2-10.31.xx` for the following reasons:

1. Security issue: "As the Unicode standard and security experts point out, ill-formed UTF can be and has been used as an attack vector. Yet the `<codecvt>` facets don't provide the safe forms of error handling as their defaults, and it is far too hard to use them in a safe way" - [quoted from here](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0618r0.html).
2. Deprecated in C++17.
3. I believe it's not JPCRE2's job to provide Unicode conversion facility to begin with.
4. These features are of very low importance considering the main goal of JPCRE2 is to work with regex not to provide conversion methods.

**Comment by wbraswell** [comment]
okay sounds good, I assume this change will not affect the way JPCRE2 match or replace works?

**Comment by neurobin** [comment]
No, this does not have any effect on match or replace.

**Comment by wbraswell** [comment]
Great!  :-)

**Comment by neurobin** [comment]
`wstring_convert` and related features ahs been removed as they deemed unnecessarily redundant as of `10.31.01`
