### ISSUE TITLE
Where the matching ends?

### ISSUE THREAD

**Issue by Kamil93** [jpcre2/jpcre2#23]
Once a while there was getEndOffset method, now there isn't. Is there another method for getting offset of where the matching finished?

tried:

```
bool result = (rm.match() > 0);

jpcre2::VecOff const* vec_eoff = rm.getMatchEndOffsetVector();
jpcre2::VecOff const& vec_eoff_ref = *vec_eoff;
		
int endOffset = vec_eoff_ref[0];
```

but it outputs segfault.

**Comment by neurobin** [comment]
Did the match succeed? if there was no match, then `vec_eoff` would be null and you would be trying to dereference a null pointer in the next line.

If the match succeeded, then can you please provide me with a short reproducible example? I will see if it's a bug. Using this method is the only way to get the end offset now.

**Comment by Kamil93** [comment]
I've just forgot to set pointer to something:

`rm.setMatchEndOffsetVector(&obj->vec_eoff);`

I was thinking each RegexMatch object has built-in VecOff object, but it needs to set our own, or I'm wrong, at least it works.

**Comment by wbraswell** [comment]
@neurobin 
Should this issue be closed?

**Comment by Kamil93** [comment]
I think so, if it is truth that user needs to set his own VecOff, then yes.

**Comment by neurobin** [comment]
yes, it seems the documentation missed to clarify this part.

**Comment by wbraswell** [comment]
@neurobin 
Are you planning to update the documentation?

**Comment by neurobin** [comment]
@wbraswell  yes

**Comment by edemattos** [comment]
Has the documentation regarding this been updated? It's still unclear to me how to get the start and end indices of a match. Could an example be added to the docs?

**Comment by neurobin** [comment]
> Has the documentation regarding this been updated?

[yes](https://docs.neuzunix.com/jpcre2/10.32.01/classjpcre2_1_1select_1_1RegexMatch.html#ad27cb923db964d7de0ba57fcb1da58fb)

[You can set the vectors with `setMatchEndOffsetVector` and `setMatchStartOffsetVector`](https://docs.neuzunix.com/jpcre2/10.32.01/classjpcre2_1_1select_1_1RegexMatch.html#ae7ee75e5dcb6231a672dfde021866cc3)

There are no examples (`VecOff` is just an array containing offset values and if set, both of those vectors will be of the same size (start and end))
