### ISSUE TITLE
unmatched optional captures at the end don't end up in numbered substring vector

### ISSUE THREAD

**Issue by mbunkus** [jpcre2/jpcre2#29]
If you have an RE that ends with an optional capture (something like `(\d+)?` and that part is not present in the subject, no element will be present in the numbered substring vector for that capture group. If more than one such group exists at the end and none of them match, then no entry is added to the vector for any of those unmatched groups.

Entries _are_ added for unmatched optional capture groups that are somewhere in the middle (meaning where there are matched capture groups following).

Here's an example program:

```c++
#include <iostream>
#include <string>

#include "jpcre2/jpcre2.hpp"

using jp = jpcre2::select<char>;

void test_match(jp::Regex &re, std::string const &subject) {
  jp::RegexMatch rm;
  jp::VecNum matches;
  auto num = rm
    .setRegexObject(&re)
    .setNumberedSubstringVector(&matches)
    .setSubject(subject)
    .match();

  std::cout << "Testing match against '" << subject << "' yielded " << num << " results\n";

  for (auto match_idx = 0u; match_idx < matches.size(); ++match_idx)
    for (auto capture_idx = 0u; capture_idx < matches[match_idx].size(); ++capture_idx)
      std::cout << "["
                << match_idx
                << "]["
                << capture_idx
                << "] "
                << matches[match_idx][capture_idx].size()
                << " "
                << matches[match_idx][capture_idx]
                << "\n";

}

int
main(int,
     char **) {
  jp::Regex re("^(\\d+)([abc])?([XYZ])?$");

  test_match(re, "42bZ");
  test_match(re, "23Z");
  test_match(re, "54b");
  test_match(re, "13");

  return 0;
}
```

And here's the output:

```
Testing match against '42bZ' yielded 1 results
[0][0] 4 42bZ
[0][1] 2 42
[0][2] 1 b
[0][3] 1 Z
Testing match against '23Z' yielded 1 results
[0][0] 3 23Z
[0][1] 2 23
[0][2] 0
[0][3] 1 Z
Testing match against '54b' yielded 1 results
[0][0] 3 54b
[0][1] 2 54
[0][2] 1 b
Testing match against '13' yielded 1 results
[0][0] 2 13
[0][1] 2 13
```

As you can see, the RE has two optional capture groups at the end. In the third test text `54b` the _last_ optioanl capture group doesn't match, the first two capture groups (of which the second is optional) do. Therefore only three elements are present in the vector (the whole match + the two captured groups). Similar for the last example text, `13`, for which the two optional capture groups at the end do not match.

However, for the example text `23Z` the first & the third capture groups match while the optional, second one does not. For that optional but unmatched second group an entry is present in the vector.

What I would expect is that there's an entry in the vector for each and every capture group. The problems with the current behavior are:

* requires the user to remember to use special-case code checking for the vector's length before accessing its member (unlike all the other capture groups for which the user can simply access `matches[0][capture_idx]`
* does not match how other regex libraries work (at least `boost::regex` and `std::regex` have one entry in their match vectors for each and every capture group)
* is highly surprising given that unmatched, optional capture groups in the middle do produce empty entries in the array

This is `jpcre2.hpp` at git revision f0349adbfe6e620023418e114c8f995a91d9086e with clang++ 10.0.1 on Arch Linux.

**Comment by neurobin** [comment]
Many thanks for taking the time to open an issue with nice elaboration. As you have said, this behavior "does not match how other regex libraries work", so I am preparing a new release 10.32.01 from which vectors will always contain all the captured groups.

master branch now contains the new update where this feature is implemented (or this bug has been fixed).

**Comment by mbunkus** [comment]
Thank you very much, especially for such a quick reaction. Much appreciated! I'll give your change a try in the next couple of days.

**Comment by mbunkus** [comment]
I've just updated to decb50173cdbb326be9ccd5ae98c925785900984, and things seem to work just fine. My vector contains the expected number of entries. Thanks again!
