### ISSUE TITLE
jpcre2 should support pcre2-32

### ISSUE THREAD

**Issue by floam** [jpcre2/jpcre2#4]
On a project I work on which also uses PCRE2, we are actually using using the 32-bit variant of the library. It was probably a mistake, but the project uses wchar_t and can't assume UTF-8.

People developing on Windows might also prefer pcre2-32 for a similar reason.

**Comment by neurobin** [comment]
The use of utf-32 is pretty rare. If I do it for utf-16, utf-32 will be supported too.

**Comment by neurobin** [comment]
wchar_t support is coming soon... @floam  I may need your help a little for testing and stuff. stay tuned... :+1:

**Comment by neurobin** [comment]
The master branch contains updated code which supports `std::string`, `std::wstring`, `std::u16string` and `std::u32string`. Currently the documentation isn't complete yet, but the examples are updated accordingly. You can get some idea there how this new API is going to work...:D

**Comment by neurobin** [comment]
[Documentation](http://docs.neurobin.org/jpcre2/index.html) complete
