### ISSUE TITLE
jpcre2.hpp: error: undefined reference to `_imp__pcre2_code_free_8'

### ISSUE THREAD

**Issue by ray-pixar** [jpcre2/jpcre2#8]
Hi
When I want to build my project I get this error:
```
jpcre2.hpp: error: undefined reference to `_imp__pcre2_code_free_8'

:-1: error:***\lib\win32\libjpcre2-8.a(libjpcre2_8_la-jpcre2.o): bad reloc address 0x28 in section `.text$_ZN6jpcre27select8IwE20getPcre2ErrorMessageEi[__ZN6jpcre27select8IwE20getPcre2ErrorMessageEi]'
```
I've linked the project against ```-ljpcre2-8 -lpcre2-8 -lpcre2-posix```
what is the problem ?

**Comment by neurobin** [comment]
`-lpcre2-posix` should be before `-lpcre2-8`.

Seems you are in a windows system. How did you build the `jpcre2` library? 

There are some quirks building jpcre2 in windows platform. If you will be using single code unit width, I would recommend using the sources for now and compile with a `-DPCRE2_CODE_UNIT_WIDTH=8` option. Also, you can get away just by defining the macro before including the hpp file and be done with,  if your IDE supports it.

I will give instructions in the readme file in a later step (when I get the time) how to build it in windows platform. Building for windows dll or static library needs some tuning..

**Comment by neurobin** [comment]
Just a test:

Make sure this program runs fine: [pcre2_match.cpp](https://gist.github.com/neurobin/5d041da046ba56c7348e6e1ef50e49c0)

Otherwise there's a problem with your PCRE2 setup.

**Comment by neurobin** [comment]
> To use the `PCRE2 POSIX` compatible library, add the `-lpcre2-posix` along with the others.

It was kinda misleading... removed it from readme. For posix compatibility, you can include the `pcre2posix.h` header ( and add the `-lpcre2-posix` if you want to use native PCRE2 posix functions), then modify the options passed to compile, match or replace() function to satisfy POSIX specification.

Actually you don't even need to include `pcre2posix.h` if you have enough knowledge about the POSIX specs, you can just modify the options to follow POSIX. But it comes with some handy constants that will make it easier.

Full POSIX compatibility with a macro definition may be added at a later stage in jpcre2. For example, you will need to define a macro like `#define JPCRE2_USE_POSIX` which will just add some extra PCRE2 options as defaults in various function calls to act it like POSIX.

**Comment by ray-pixar** [comment]
> -lpcre2-posix should be before -lpcre2-8.
> 
> On windows you also need to define #define PCRE2_STATIC before including jpcre2.hpp if you are linking against static library.

I've did it but it still does not work!.

> There are some quirks building jpcre2 in windows platform. If the above doesn't work, you can use it with the sources and compile with -DPCRE2_CODE_UNIT_WIDTH=8.

I think I should do it. Thanks for the advice.

**Comment by ray-pixar** [comment]
i've build the JPCRE2 with following command, now it seems ok. but I should test it:
```
make CXXFLAGS="-fpermissive -DPCRE2_STATIC -DPCRE2_CODE_UNIT_WIDTH=8"
```

**Comment by ray-pixar** [comment]
I'm getting this exception:
```
Error: EXCEPTION_ACCESS_VIOLATION
?? ??:0
pcre2_substitute_8 at c:\Dev\lib\pcre2\pcre2-10.22/src/pcre2_substitute.c:378
```

for following code:
```c++
std::cout<<jpcre2::select8<char>::Regex("\\d+").replace("I am digits 1234","5678", "g") << endl;
```

**Comment by ray-pixar** [comment]
something's wrong with buffer allocation. At following line, the buffer size is ```-1```:
```c++
PCRE2_SIZE outlengthptr = (PCRE2_SIZE) buffer_size;
```
when I replace **buffer_size** with **1024*32** it goes well.

**Comment by ray-pixar** [comment]
```pcre2_substitute``` does not return ```PCRE2_SUBSTITUTE_OVERFLOW_LENGTH``` flag. It throws exception at first run.

**Comment by ray-pixar** [comment]
I think the problem is with following macro in PCRE2 lib:
```c++
/* This macro checks for space in the buffer before copying into it. On
overflow, either give an error immediately, or keep on, accumulating the
length. */

#define CHECKMEMCPY(from,length) \
  if (!overflowed && lengthleft < length) \
    { \
    if ((suboptions & PCRE2_SUBSTITUTE_OVERFLOW_LENGTH) == 0) goto NOROOM; \
    overflowed = TRUE; \
    extra_needed = length - lengthleft; \
    } \
  else if (overflowed) \
    { \
    extra_needed += length; \
    }  \
  else \
    {  \
    memcpy(buffer + buff_offset, from, CU2BYTES(length)); \
    buff_offset += length; \
    lengthleft -= length; \
    }
```

**Comment by ray-pixar** [comment]
I found it. I replaced following line:
```c++
const SIZE_T SUBSTITUTE_RESULT_INIT_SIZE = std::numeric_limits<int>::max();
```
with this:
```c++
const SIZE_T SUBSTITUTE_RESULT_INIT_SIZE = 0;
```

Now it works.

**Comment by neurobin** [comment]
Setting it to 0 will have some performance degradation. The pcre2_substitute function will be called twice. You may give an initial big enough buffer with `RegexReplace::setBuffersize()` function to make it a single call operation.

**Comment by ray-pixar** [comment]
so, It is an **undocumented** thing in your lib! you should had mentioned it.

**Comment by ray-pixar** [comment]
I think passing ```string size * 2``` as default parameter is better than setting default buffer size as ```std::numeric_limits<int>::max()```.

**Comment by neurobin** [comment]
Actually, it is not possible to estimate the size without knowing how the replace string is made up. A simple example like this needs more than string size*2 buffer : `$0 some text $0`.

You may change the line to 

```cpp
const SIZE_T SUBSTITUTE_RESULT_INIT_SIZE = (std::numeric_limits<int>::max)();
```
It will probably solve the problem.

**Comment by ray-pixar** [comment]
It seems that you could implemet **Regex** and **RegexReplace** classes with **template classes** instead of using _macros_ that makes debugging very very hard.

**Comment by ray-pixar** [comment]
I don't think using ```std::numeric_limits<int>::max();``` or ```0``` is equal at practice.

**Comment by ray-pixar** [comment]
I think using ```std::numeric_limits<int>::max();``` or ```0``` is equal at practice.

**Comment by neurobin** [comment]
> I think using std::numeric_limits<int>::max(); or 0 is equal at practice

Can you explain?

**Comment by neurobin** [comment]
>  Regex and RegexReplace classes with template classes

It would be OK as long as single code unit width is concerned. But when you are using multi-code unit width, things become complicated and keeping the code together in one place becomes difficult (template specialization).

But of course, if you think you can templatize the whole library without using macros and still support multi-code unit width without writing any code twice (code must be in one place), then please go ahead. I will greatly appreciate any improvement that is made.

**Comment by ray-pixar** [comment]
> 
> 
>     I think using std::numeric_limits::max(); or 0 is equal at practice
> 
> Can you explain?
> 

Memory allocation with ```max()``` will be failed by **malloc** and equals **NULL**, and allocation with ```0``` is equals **NULL**.

**Comment by ray-pixar** [comment]
> 
> 
>     I think using std::numeric_limits::max(); or 0 is equal at practice
> 
> Can you explain?
> 

Memory allocation with ```max()``` is failed by **malloc** and equals **NULL**, and allocation with ```0``` is equals **NULL**. But in Windows, they behave differently. PCRE2 with ```max()``` does crash.

**Comment by ray-pixar** [comment]
> But of course, if you think you can templatize the whole library without using macros and still support multi-code unit width without writing any code twice (code must be in one place), then please go ahead. I will greatly appreciate any improvement that is made.

I've implemented a sample with **Nested Includes**. It works but the problem is that IDE autocomplete feature only works for the first class definition.

**Comment by neurobin** [comment]
Initially I had three separate cpp and header files for three classes `Regex`, `RegexMatch` and `RegexReplace`. But it didn't make much of a sense to deal with circular dependencies and also it's not a good practice to put codes that are dependent to each other in different modules. A single module should contain all of it's functionalities and thus posses completeness. What can be done, is to make it a header only (single header) library and templatize all of it (even the code unit width). I don't have any strategy for it now :D. But it requires template specialization which I want to avoid because of possible code duplication.

Also there is another way, that is, separating RegexMatch and RegexReplace class completely and allowing users to create objects and passing the Regex object reference to perform match or replace, but that definitely goes against my principle (one object for everything without any extra price to pay).

**Comment by ray-pixar** [comment]
It seems that It's better to leave it as it is, because the code's conversion cost is high!

**Comment by neurobin** [comment]
Well, making it a header only library was kinda tempting, so I went ahead and done it. Now it has two mentionable features:

1. No need for building libraries any more, just include and use.
2. Provides a way to [code with portability](https://github.com/jpcre2/jpcre2#portable-coding) in mind.
