### ISSUE TITLE
Match Evaluator

### ISSUE THREAD

**Issue by ray-pixar** [jpcre2/jpcre2#9]
Hi.
C# has a powerful Regex replace function that supports **MatchEvaluator**. Please implement this feature in your library.

code example
```C#
string result = Regex.Replace(val, "(<img[^><]+src=)(\"|')([^'\"]*)", new MatchEvaluator((Match m) =>
                    {
                        return $"$1$2{{{book_sid}}}{m.Groups[3]}]";
                    }), RegexOptions.IgnoreCase);
```

**Comment by ray-pixar** [comment]
you should call **developer's callback** on each match and replace.

**Comment by neurobin** [comment]
Can you explain the advantages and importance of this feature with some examples?

**Comment by ray-pixar** [comment]
For example you need search and replace with a string that needs you query your database to fetch data.

**Comment by ray-pixar** [comment]
Are you motivated to add this feature ?
Should I wait for the update ?

**Comment by neurobin** [comment]
Currently I can not allocate enough time for this project. If I decide to add it, it probably won't be within a month or two..

**Comment by ray-pixar** [comment]
I've implemented a sample with *MatchEvaluator* feature. Please take a look and consider it to include in your lib, if it's useful.

```c++
typedef string (*MatchEvaluator)(const vector<string>& matched_groups);

bool replaceExAll(string& s, const string& replace_this_reg_ex, MatchEvaluator me, bool case_sensitive)
{
    if(me == NULL)
        return false;
    jp8::VecNum vec_num;
    jp8::Regex re(replace_this_reg_ex);
    jp8::RegexMatch& m = re.initMatch();

    if(!case_sensitive)
        m.addPcre2Option(PCRE2_CASELESS);

    m.setSubject(s)
            .setNumberedSubstringVector(&vec_num)
            .setFindAll();

    size_t count = m.match();

    if(count == 0 && re.getErrorNumber() != 0 &&
           re.getErrorNumber() != PCRE2_ERROR_BADOFFSET)   
 // I don't know why it returns PCRE2_ERROR_BADOFFSET error!!! please check it.
        return false;

    if(count == 0)
        return true;

    string::size_type pos = 0, last = 0;
    ostringstream ss;
    for(size_t i=0; i<vec_num.size(); i++ )
    {
        string rep = me(vec_num[i]);
        pos = s.find(vec_num[i][0], pos);
        ss << s.substr(last, pos-last);
        ss << rep;
        pos = last = pos + vec_num[i][0].size();
    }
    s = ss.str();
    return true;
}
```

**Comment by ray-pixar** [comment]
Usage:
```c++
string s = "++++filemap://{sound_1}/test/file.wav,+++ filemap://{sound__2}/test/file.wav,++++ filemap://{sound_3}/test/file.wav ,++++++";
    cout << "Before: " << s << endl;
U::String::replaceExAll(s, "(filemap://)(\\{([^\\}\\{]+)\\})([^,]*)", [](const vector<string>& m)
    {
       cout << "g0=" << m[0] << endl;
       cout << "g1=" << m[1] << endl;
       cout << "g2=" << m[2] << endl << endl;

       return m[2] + " | ";
    });

    cout << "After: " << s << endl;
```

**Comment by ray-pixar** [comment]
Surely you need to change this code. It's just a sample implementation of *MatchEvaluator*.
thanks

**Comment by neurobin** [comment]
You can not rely on error number unless you use resetErrors (though it was not necessary in your example):
```cpp
size_t count = m.resetErrors().match();
```
BADERROR offset needs some further investigation though.

<hr>

Actually I have plans to improve this error facility a bit. Currently the Regex object holds all the errors, but match object and replace object should hold their respective errors while Regex object should only care about the compile error.

And I like your approach. I am definitely motivated to implement this MatchEvaluator feature. But currently I am not able to spare time for this project, so it may come in late. This is how I have planned for now:

1. Match evaluator will allow use of all three match vectors, something like `(*MatchEvaluator)(vector<string>* m_num vector<string,string>* m_nas, vector<string, size_t>* m_ntn)`
2. I haven't thought yet, if I should use a class or just plain function pointer. A new class would definitely give much more powerful interface while function pointer will make it the simplest.

Improvements:

1.  Instead of hardcoding `std::string` you can use the typedef `jp8::String` which will give you a portable approach, for `char` it's the same as `std::string`.
2. `find()` and `substr()` won't handle unicode strings properly, for unicode you should use the RegexReplace::replace() function to perform replacement and it involves sanitizing the replacement string i.e replacing all `$` to `$$` before passing it to `replace()`.

**Comment by ray-pixar** [comment]
Thank you for the decision.
*Note*: we absolutely avoid using something like `string.find` function because it does not work for regex patterns like `look ahead` patterns `(?=xxx)`
If you want to use `RegexReplace::replace()` function consider supporting `PCRE2_SUBSTITUTE_EXTENDED` functionality. More info is [here](http://www.regular-expressions.info/replaceconditional.html#boost).
I'm worry about `RegexReplace::replace()`  because it may increase cost of `find and replace` operation unnecessarily. It's better to store index of match items to `VecNum` and make a substring using `index` and `matched length`. Then we can replace results without using `RegexReplace::replace()` and fast thing up.

**Comment by neurobin** [comment]
As JPCRE2 is just a wrapper,  `PCRE2_SUBSTITUTE_EXTENDED` is supported if your PCRE2 version supports it and the behavior will be the same. You can pass this option with `addPcre2Option()` or the modifier 'x' with `addModifier()`

**Comment by neurobin** [comment]
> I'm worry about RegexReplace::replace() because it may increase cost of find and replace operation unnecessarily. It's better to store index of match items to VecNum and make a substring using index and matched length. Then we can replace results without using RegexReplace::replace() and fast things up.

Yap, `RegexReplace::replace()` will require sanitizing the `$`s first and that reduces the performance. I will probably have to write a new replace function for this...

**Comment by ray-pixar** [comment]
> As JPCRE2 is just a wrapper, PCRE2_SUBSTITUTE_EXTENDED is supported if your PCRE2 version supports it and the behavior will be the same. You can pass this option with addPcre2Option() or the modifier 'x' with addModifier()

Yes, currently I'm doing it. I just said it because if you want to add an explicit function.


> 
> Oh, I forgot to mention, the following code will have no effect:
> 
> m.addPcre2Option(PCRE2_CASELESS);
> 
> caseless needs to be compiled in the pattern itself i.e PCRE2_CASELESS is a compile time only option.
> 

Thanks a lot for `compile()` hint.

**Comment by neurobin** [comment]
> I just said it because if you want to add an explicit function

It will come with a different name and I will try to mimic the `pcre2_substitute()` function

**Comment by ray-pixar** [comment]
`C++ lambda` object has limitation on passing as function argument. If it captures some variable, it won't compile. please check [this link](http://stackoverflow.com/a/17305457/365229) as an alternative solution. `(std::function)`

**Comment by neurobin** [comment]
I don't want to force c++11 on anyone, I will use function pointer or a class.

**Comment by ray-pixar** [comment]
BTW, I've updated `replaceRegex` function. Now it supports `labmda with captures` functions.

you can implement this feature as a bonus for c++11 fans.

**Comment by neurobin** [comment]
MatchEvaluator is available now. The callback function always returns a literal string, thus extended functionality like pcre2_substitutes' extended options, group name with `$` are not available and there's actually no need for that as you will have complete access to all types of captured groups inside the callback function. Further string processing would be redundant and inefficient. If someone needs pcre2 extended like functionality, he can easily implement it inside the callback function with just some conditionals, no string parsing needed.

**Comment by ray-pixar** [comment]
thanks for adding this feature.

**Comment by neurobin** [comment]
The PCRE2 extended functionality seemed useful, and it isn't that easy to implement inside a callback function. Thus callback facility has been added to the `replace()` function as well, which will process the returned string from the callback with `pcre2_substitute` (by passing the matched part as subject and the returned string as replacement)
